[[ReferenceBLAS]]
arch = "aarch64"
git-tree-sha1 = "c6b0b8998918c2771012ba1a9a49c108ccc3539e"
libgfortran_version = "5.0.0"
os = "macos"

    [[ReferenceBLAS.download]]
    sha256 = "ded4911c85425ba7e97907d7c131053c74a61b977f1facd2cc2f47b64c771ec3"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "aarch64"
git-tree-sha1 = "d284eef76925d7582215c80ead67d49899859c65"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS.download]]
    sha256 = "0c6fc18ab724109b07c236e4fc0dff0abce811a4793fa3fd6ead90ab660a5806"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "aarch64"
git-tree-sha1 = "74503071c6d65ac617f11d9b34d541c5d588a758"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS.download]]
    sha256 = "d7fafc145baa5bbf7a54e9479c6620f875cda426a31891704ec55c16ee34b16c"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "aarch64"
git-tree-sha1 = "d670b3aa7ee0bfce676c4c3a3cfff9e2b934b63a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[ReferenceBLAS.download]]
    sha256 = "fbc8a89f52c0879bcb3c6e51be2af063cff72330ec711c29209d75f72330962f"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d151706a7590d684c4e771609dc8d76d8856f85f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS.download]]
    sha256 = "2009041e1286e69ea6cfd7924760a61e666984ccdc79b4355cc6a0d4344e04d5"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "095d371ea4c2289d54389a1906aaeda327942335"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS.download]]
    sha256 = "3fef4c9554e5142909e49db6b2627ca122a66f92a740c9d85233ab78abce956b"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "48b8970c402344dd4283fdf45af1675aac82a1c9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS.download]]
    sha256 = "49964e4d50d052d974dc101da0d96b8c07656883c583dbf89a14200bb3e356c9"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d58bfa332c4d059cceda1e1f3e46b858bb1d4fec"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS.download]]
    sha256 = "7aafa89d9b4899d0751af59a0d1633172182cd0293d9cb0a45ab4272dc1a62c7"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "i686"
git-tree-sha1 = "51b1f911420212af2d86decf3c67f95d24f8a031"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS.download]]
    sha256 = "d71055a2667ba29d61adb6952abaf7fc3986acf512b0e04cba4066c45048aa41"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.i686-linux-gnu-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "i686"
git-tree-sha1 = "0fb06c75706910236643a95e25dfa3372257fcbf"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS.download]]
    sha256 = "7ca2d757444ff6eab31f8a5ce6fabad06c347bd950de7f477587e135ecd73d69"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.i686-linux-musl-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "i686"
git-tree-sha1 = "436669cd214532d0b92259c3ca9364239b93a92e"
libgfortran_version = "5.0.0"
os = "windows"

    [[ReferenceBLAS.download]]
    sha256 = "19df21c02af90729073bd38ebd45282a64a095a3e99f5b9fb11a57fd8159b3a7"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "powerpc64le"
git-tree-sha1 = "f122f4bd3488067bdede618e5ef99be0ff58b4d0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS.download]]
    sha256 = "4589d7fbb21e92e7b8e7769f8159437087fb4d8fb7f67657ae3845c12c6219dd"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "riscv64"
git-tree-sha1 = "7664c0e13973436e09a41e79a2d9b3ad8c1846ec"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS.download]]
    sha256 = "bd10ac71da404ce5856971b3b5fa6d0e264e522d515e3cadcede5902ac7811ce"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.riscv64-linux-gnu-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "x86_64"
git-tree-sha1 = "b4c44d528443be792d1dfb9be12b3b4f310b917a"
libgfortran_version = "5.0.0"
os = "macos"

    [[ReferenceBLAS.download]]
    sha256 = "9dd2b994374559d2ddebef7a74ebf91b0058448c4100a59e529616c3610b2647"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "x86_64"
git-tree-sha1 = "209275fff9e3c052c2dbcbd9b35a281924686b9d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS.download]]
    sha256 = "f34f557c1fe41e1b409671d83b70e896812a9e53bb44a7148f10903910d0c4a6"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "x86_64"
git-tree-sha1 = "81fd942e4f3c54f2edffd2e71185207b6390ad5c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS.download]]
    sha256 = "eefac855c45198932eac3e5996f3304aefa127c176d53718d49cf8cd9743c0c5"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "x86_64"
git-tree-sha1 = "b8fd2fc4a983628c6c442017807f6058aa52da35"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[ReferenceBLAS.download]]
    sha256 = "86b048207f8a8bef569aeb4fd54073af835ceaca39b75fa848caa0938f3b17f8"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[ReferenceBLAS]]
arch = "x86_64"
git-tree-sha1 = "af63ed6d6dd2d70bfca15e00b2554c9aeaebca9c"
libgfortran_version = "5.0.0"
os = "windows"

    [[ReferenceBLAS.download]]
    sha256 = "bda2a6bc7b7e50bb393dd35cd59ec189f7f4f49f0db6df7cb0ae3ce9d88f3b83"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS_jll.jl/releases/download/ReferenceBLAS-v3.12.1+1/ReferenceBLAS.v3.12.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
